version: '3'
services:
  app:
    image: ghcr.io/devplayer0/octolxd:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - OCTOLXD_LOG_LEVEL=debug
      - OCTOLXD_HTTP_LISTEN_ADDRESS=:8080
    ports:
      - 8080:8080
    volumes:
      - .:/usr/local/src/octolxd
      - ./config.yaml:/run/config/octolxd.yaml:ro
    user: '1000:1000'
