apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octolxd.fullname" . }}
  labels:
    {{- include "octolxd.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  octolxd.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
